### ISSUE TITLE
Wheel support

### ISSUE THREAD

**Issue by kevin-brown** [hamstah/ukpostcodeparser#10]
http://pythonwheels.com/

Right now, only the `tar.gz` file is being distributed on PyPI for [ukpostcodeparser](https://pypi.python.org/pypi/ukpostcodeparser), which isn't _that much_ of an issue, but it does add some time to installing the package.

This package should be compatible with the Wheel format, considering it doesn't appear to have any C dependencies and it is compatible with both Python 2 and 3. As a result, you should only need to generate a universal wheel and then everyone (on all systems) will get the ability to install ukpostcodeparser with just the wheel, without having to do any extra work.

**Comment by hamstah** [comment]
Hey
Good idea. I've uploaded wheels for py2 and py3.
py2 is missing my sig because I forgot to upload it the first time but it won't let me re-upload the same version. 

Will do for the next version unless the missing sig is causing issues, in which case please re-open an issue.

Thanks!
