### ISSUE TITLE
Any thoughts on merging simonhayward/ukpostcodeparser master branch?

### ISSUE THREAD

**Issue by lvisintini** [hamstah/ukpostcodeparser#3]
https://github.com/simonhayward/ukpostcodeparser has a few code changes that should be nice to have in the main repo and the official pip package.

Any reason why it has not been merged?

**Comment by hamstah** [comment]
Hi
I wasn't aware of the fork.
Feel free to submit a pr and I will merge it, otherwise I will do it in the
next few days when. I have some time.
Thanks

**Comment by hamstah** [comment]
Thanks for the PR, now merged and upload to pypi
