### ISSUE TITLE
license

### ISSUE THREAD

**Issue by siddharthist** [hamstah/ukpostcodeparser#7]
I can't seem to find the license for this code. From http://choosealicense.com/no-license [1]:

> You’ll have to check with your own legal counsel regarding your particular project, but generally speaking, the absence of a license means that default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work.

Did you intend for this code to be open source? If so, can you upload a license, or point me to it?

Thanks!

[1]: See also: the Berne Convention, the international law: http://zvon.org/law/r/bern.html#intro

**Comment by hamstah** [comment]
Good point.
The initial code isn't from me, so I'll double check with Simon, but yes it is definitely intended to be open source. If Simon is ok with it I will make it MIT.

**Comment by hamstah** [comment]
@brunns Are you ok with the above suggestion?

**Comment by brunns** [comment]
+1 for MIT from me.

**Comment by kevin-brown** [comment]
I see it's marked as MIT in the `setup.py` file, but this still appears to be missing a LICENSE file or other visible marks of what the license actually is.

**Comment by hamstah** [comment]
Hey sorry for the long delay fixing this.
The repo is now updated with the file.
